---

roles:
  - name: docker_install
    scm: git
    src: git@github.com:webdrone-infra/asbl-docker_install.git
    version: main

  - name: apt_packages_install
    scm: git
    src: https://github.com/webdrone-infra/asbl-apt_packages_install.git
    version: main

collections:
  - name: scaleway.scaleway
  - name: community.general
  - name: ansible.posix


