---

roles:
  - name: docker_install
    scm: git
    src: https://github.com/tiny-company/asbl-docker_install.git
    version: main

  - name: apt_packages_install
    scm: git
    src: https://github.com/tiny-company/asbl-apt_packages_install.git
    version: main

collections:
  - name: community.general
  - name: ansible.posix


