---
# Description : set docker daemon configuration
# file : _configure_docker.yml
# from : https://github.com/mullholland/ansible-role-docker/blob/main/tasks/configure.yml
# from : https://github.com/nickjj/ansible-docker/blob/master/tasks/main.yml

- name: Create Docker configuration directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
    owner: "{{ root_user }}"
    group: "{{ root_user }}"
    mode: "0755"
  loop: "{{ docker_opts_path }}"

- name: Configure Docker daemon options (json)
  ansible.builtin.template:
    src: "etc/docker/daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    backup: true
    owner: "{{ root_user }}"
    group: "{{ root_user }}"
    mode: "0644"
    validate: dockerd --validate --config-file %s
  notify: ["restart docker"]

- name: Configure Docker systemd options (flags, env var, ..)
  ansible.builtin.template:
    src: "etc/systemd/system/docker.service.d/options.conf.j2"
    dest: "/etc/systemd/system/docker.service.d/options.conf"
    owner: "{{ root_user }}"
    group: "{{ root_user }}"
    mode: "0644"
  notify: ["Reload systemd daemon", "restart docker"]
