---
# Description : configure docker hub ids
# file : _set_docker_hub.yml
# source : https://docs.ansible.com/ansible/latest/collections/community/docker/docker_login_module.html
# from : https://github.com/nickjj/ansible-docker/blob/master/tasks/main.yml

- name: assert docker registry credentials are defined
  ansible.builtin.assert:
    that:
      - "dockerhub_username is defined and dockerhub_username|length > 0"
      - "dockerhub_password is defined and dockerhub_password|length > 0"
    fail_msg: "'dockerhub_username' or 'dockerhub_password' vars is empty"

# It's safe to ignore no-log-password because we're removing the password from
# the output with the loop_control property.
- name: Manage Docker registry login credentials
  community.docker.docker_login:
    registry_url: "{{ item.registry_url | d(omit) }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    email: "{{ item.email | d(omit) }}"
    reauthorize: "{{ item.reauthorize | d(omit) }}"
    config_path: "{{ item.config_path | d(omit) }}"
    state: "{{ item.state | d('present') }}"
  loop: "{{ docker__registries }}"
  loop_control:
    label: '{{ {"registry_url": item.registry_url | d("https://index.docker.io/v1/"), "username": item.username, "state": item.state | d("present")} }}'  # yamllint disable-line rule:line-length
  when: item.username | d() and item.password | d()
  become: true
  become_user: "{{ docker__login_become_user | d('root') }}"
  vars:
    ansible_python_interpreter: "{{ '/usr/local/bin/python3-docker' }}"