---
# Description : install and configure docker service
# file : main.yml

## delete old obsoletes packages
- import_tasks: _remove_obsolete_docker.yml
  become: true
  become_user: "{{ root_user }}"
  tags: [_remove_obsolete_docker]
  when: docker_set_dockerhub

- name: Creates docker data root path
  become: true
  become_user: "{{ root_user }}"
  ansible.builtin.file:
    path: "{{ docker_data_root }}"
    state: directory

## docker rootfull
- name: Install and configure rootful Docker
  become: true
  become_user: "{{ root_user }}"
  ansible.builtin.import_tasks:
    file: _install_docker_rootful.yml
  tags: [_install_docker_rootful]
  when: docker_rootfull

## docker rootless (WIP)
# - name: Install and configure rootless Docker
#   ansible.builtin.import_tasks:
#     file: _docker_install_rootless.yml
#   tags: [_docker_rootless]
#   when: not docker_rootfull

- name: configure python with docker
  ansible.builtin.import_tasks:
    file: _configure_python_docker.yml
  tags: [_configure_python_docker]

# create docker user
- name: configure docker user and group
  become: true
  become_user: "{{ root_user }}"
  ansible.builtin.import_tasks:
    file: _user_docker_configuration.yml
  tags: [_user_docker_configuration]

# configure docker
- name: configure docker daemon
  become: true
  become_user: "{{ root_user }}"
  ansible.builtin.import_tasks:
    file: _configure_docker.yml
  tags: [_configure_docker]

# configure dockerhub ids
- import_tasks: _set_docker_hub.yml
  tags: [_set_docker_hub]
  when: docker_set_dockerhub

# setting docker cron job
- import_tasks: _set_docker_cronjob.yml
  tags: [_set_docker_cronjob]
  when:
    - docker_cron_jobs is defined
    - docker_cron_jobs is iterable