---
- name: restart sshd
  become: true
  become_user: root
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: restart docker
  become: true
  become_user: root
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Reload systemd daemon
  become: true
  become_user: root
  ansible.builtin.systemd:
    daemon_reload: true
